version: "3.8"
services:
  app:
    image: todo-front
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./src:/app/src:ro # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 5000:3000
    container_name: todo-front # This will name the container hello-front-dev
    env_file:
      - ./.env
    
