FROM node:16 AS build-stage

WORKDIR /usr/src/app

COPY . .

RUN npm ci

RUN npm run build

RUN npm install -g serve

RUN npm run test

CMD ["serve", "build"]
CMD ['npm', 'run', 'test']

