version: '3.8'

services:
  frontend:
    stdin_open: true
    tty: true
    image: bloglist-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: bloglist-frontend
  backend:
    image: bloglist-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    container_name: bloglist-backend
    environment: 
      - MONGODB_URI=mongodb+srv://fullstackopen:0g94MC149V7LzEna@cluster0.qgqb3at.mongodb.net/blogilista?retryWrites=true&w=majority
      - SECRET=lkdjsalkdjsaldhjasöldih24091347fj
      - PORT=3003
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend