version: '3.8'            # Version 3.8 is quite new and should work

services:
  server:                   
    image: todo-backend-server   # Declares which image to use
    build: .              # Declares where to build if image is not found
    ports:                # Declares the ports to publish
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://the_username:the_password@server:27017/the_database
      - REDIS_URL=redis://server:6379
